version: '3.3'

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - ${POSTGRES_PORT}:5432
    env_file:
      - '.env'
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    env_file:
      - '.env'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
